# Generated by Django 2.0.3 on 2018-05-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0003_auto_20180522_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constructionpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d')),
            ],
        ),
    ]
