# Generated by Django 2.0.5 on 2018-05-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0005_tos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('use', models.BooleanField()),
                ('infor', models.BooleanField()),
                ('phoneno', models.IntegerField()),
                ('phoneno1', models.IntegerField()),
                ('phoneno2', models.IntegerField()),
            ],
        ),
    ]
